apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-dep
spec:
  selector:
    matchLabels:
      app: back-dep
  replicas: 2
  template:
    metadata:
      labels:
        app: back-dep
    spec:
      containers:
        - name: back-dep
          image: chedysk/back
          ports:
            - containerPort: 8085
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_NAME
              value: elearning
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: root

---
# Service definition to expose the backend deployment
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: back-dep
spec:
  type: NodePort
  selector:
    app: back-dep
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
      nodePort: 30002