---
- name: Copy and apply YAML files to master machine
  hosts: master
  tasks:
    - name: Copy YAML files from local machine to master machine
      copy:
        src: "{{ item }}"
        dest: "/home/master/{{ item }}"
      loop:
        - mysql.yaml
        - back.yaml

    - name: Apply YAML files on master machine
      command: kubectl apply -f "/home/master/{{ item }}"
      loop:
        - mysql.yaml
        - back.yaml